version: '3.8'

services:
  app:
    build: .
    container_name: tinyvault-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL:-sqlite+aiosqlite:///./data/tinyvault.db}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DEBUG=${DEBUG:-false}
      - EC2_HOST=${EC2_HOST:-localhost}
      - APP_NAME=${APP_NAME:-TinyVault}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  logs: 