version: '3.8'

services:
  app:
    build: .
    container_name: tinyvault-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tinyvault-network

volumes:
  data:
  logs:

networks:
  tinyvault-network:
    driver: bridge