"""add test field to user table

Revision ID: 3cc3c3543fc4
Revises: 001
Create Date: 2025-08-12 10:45:18.059480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc3c3543fc4'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('idx_items_owner_user_id')
        batch_op.drop_index('idx_items_short_code')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.String(length=100), nullable=True))
        batch_op.drop_index('idx_users_telegram_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_telegram_user_id', ['telegram_user_id'], unique=False)
        batch_op.drop_column('test_field')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('idx_items_short_code', ['short_code'], unique=False)
        batch_op.create_index('idx_items_owner_user_id', ['owner_user_id'], unique=False)

    # ### end Alembic commands ### 