"""remove test field from user table

Revision ID: 634d648976e2
Revises: 3cc3c3543fc4
Create Date: 2025-08-12 10:46:12.147107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634d648976e2'
down_revision = '3cc3c3543fc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ### 