---
- name: Deploy TinyVault app from GitHub with Docker
  hosts: tinyvault_prod
  become: yes
  gather_facts: no
  tasks:
    - name: Clean up problematic Docker repository
      raw: |
        sudo yum-config-manager --disable docker-ce-stable || true
        sudo rm -f /etc/yum.repos.d/docker-ce.repo || true
      changed_when: false

    - name: Update yum cache
      raw: sudo yum update -y
      changed_when: false

    - name: Install required packages
      raw: |
        sudo yum install -y yum-utils device-mapper-persistent-data lvm2 wget unzip --allowerasing
      changed_when: false

    - name: Install Docker for Amazon Linux
      raw: |
        sudo yum install -y docker
        sudo service docker start
        sudo chkconfig docker on
        sudo groupadd docker || true
        sudo usermod -a -G docker ec2-user
      changed_when: false

    - name: Install Docker Compose
      raw: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
      changed_when: false

    - name: Create application directory
      raw: sudo mkdir -p /opt/tinyvault && sudo chown ec2-user:ec2-user /opt/tinyvault
      changed_when: false

    - name: Download project from GitHub
      raw: |
        cd /opt
        wget https://github.com/mo7amedgom3a/TinyVault/archive/refs/heads/main.zip
        unzip main.zip
        # copy the content of TinyVault-main to /opt/tinyvault
        sudo cp -r TinyVault-main/* /opt/tinyvault/
        rm -rf TinyVault-main main.zip
      changed_when: false

  
    - name: Build Docker image
      raw: |
        cd /opt/tinyvault
        sudo docker build \
          --build-arg ADMIN_API_KEY="{{ lookup('env', 'TINYVAULT_ADMIN_API_KEY') | default('', true) }}" \
          --build-arg DB_URL="{{ lookup('env', 'TINYVAULT_DB_URL') | default('sqlite+aiosqlite:///./data/tinyvault.db', true) }}" \
          --build-arg TELEGRAM_BOT_TOKEN="{{ lookup('env', 'TINYVAULT_TELEGRAM_BOT_TOKEN') | default('', true) }}" \
          --build-arg WEBHOOK_SECRET="{{ lookup('env', 'TINYVAULT_WEBHOOK_SECRET') | default('', true) }}" \
          --build-arg DEBUG="{{ lookup('env', 'TINYVAULT_DEBUG') | default('false', true) }}" \
          --build-arg EC2_HOST="{{ lookup('env', 'EC2_HOST') | default('localhost', true) }}" \
          --build-arg APP_NAME="{{ lookup('env', 'TINYVAULT_APP_NAME') | default('TinyVault', true) }}" \
          -t tinyvault-app .
      changed_when: true

    - name: Run Docker container
      raw: |
        sudo docker stop tinyvault-app || true
        sudo docker rm tinyvault-app || true
        sudo docker run -d \
          --name tinyvault-app \
          --restart always \
          -p 80:8000 \
          -e DB_URL="{{ lookup('env', 'TINYVAULT_DB_URL') | default('sqlite+aiosqlite:///./data/tinyvault.db', true) }}" \
          -e TELEGRAM_BOT_TOKEN="{{ lookup('env', 'TINYVAULT_TELEGRAM_BOT_TOKEN') | default('', true) }}" \
          -e ADMIN_API_KEY="{{ lookup('env', 'TINYVAULT_ADMIN_API_KEY') | default('', true) }}" \
          -e WEBHOOK_SECRET="{{ lookup('env', 'TINYVAULT_WEBHOOK_SECRET') | default('', true) }}" \
          -e DEBUG="{{ lookup('env', 'TINYVAULT_DEBUG') | default('false', true) }}" \
          -e EC2_HOST="{{ lookup('env', 'EC2_HOST') | default('localhost', true) }}" \
          -e APP_NAME="{{ lookup('env', 'TINYVAULT_APP_NAME') | default('TinyVault', true) }}" \
          tinyvault-app
      changed_when: true
    - name: Run docker Compose
      raw: |
        cd /opt/tinyvault
        sudo docker-compose down || true
        sudo docker-compose build
        sudo docker-compose up -d
        

    - name: Wait for container to be ready
      pause:
        seconds: 10