---
- name: Deploy TinyVault app from GitHub with Docker
  hosts: tinyvault_prod
  become: yes
  gather_facts: no
  tasks:
    - name: Clean up problematic Docker repository
      raw: |
        sudo yum-config-manager --disable docker-ce-stable || true
        sudo rm -f /etc/yum.repos.d/docker-ce.repo || true
      changed_when: false

    - name: Update yum cache
      raw: sudo yum update -y
      changed_when: false

    - name: Install required packages
      raw: |
        sudo yum install -y yum-utils device-mapper-persistent-data lvm2 wget unzip --allowerasing
      changed_when: false

    - name: Install Docker for Amazon Linux
      raw: |
        sudo yum install -y docker
        sudo service docker start
        sudo chkconfig docker on
        sudo groupadd docker || true
        sudo usermod -a -G docker ec2-user
      changed_when: false

    - name: Install Docker Compose
      raw: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
      changed_when: false

    - name: Create application directory
      raw: sudo mkdir -p /opt/tinyvault && sudo chown ec2-user:ec2-user /opt/tinyvault
      changed_when: false

    - name: Download project from GitHub
      raw: |
        cd /opt
        wget https://github.com/mo7amedgom3a/TinyVault/archive/refs/heads/main.zip
        unzip main.zip
        # copy the content of TinyVault-main to /opt/tinyvault
        sudo cp -r TinyVault-main/* /opt/tinyvault/
        rm -rf TinyVault-main main.zip
      changed_when: false

    - name: Set proper permissions
      raw: sudo chown -R ec2-user:ec2-user /opt/tinyvault
      changed_when: false

    - name: Create .env file for TinyVault from environment variables
      raw: |
        cd /opt/tinyvault && \
        cat > .env << 'EOF'
        DB_URL=${TINYVAULT_DB_URL:-sqlite+aiosqlite:///./data/tinyvault.db}
        TELEGRAM_BOT_TOKEN=${TINYVAULT_TELEGRAM_BOT_TOKEN}
        ADMIN_API_KEY=${TINYVAULT_ADMIN_API_KEY}
        WEBHOOK_SECRET=${TINYVAULT_WEBHOOK_SECRET}
        DEBUG=${TINYVAULT_DEBUG:-false}
        EC2_HOST=${EC2_HOST:-localhost}
        APP_NAME=${TINYVAULT_APP_NAME:-TinyVault}
        EOF
        chmod 600 .env
      changed_when: false
      environment:
        TINYVAULT_DB_URL: "{{ lookup('env', 'TINYVAULT_DB_URL') | default('sqlite+aiosqlite:///./data/tinyvault.db', true) }}"
        TINYVAULT_TELEGRAM_BOT_TOKEN: "{{ lookup('env', 'TINYVAULT_TELEGRAM_BOT_TOKEN') | default('', true) }}"
        EC2_HOST: "{{ lookup('env', 'EC2_HOST') | default('localhost', true) }}"
        TINYVAULT_ADMIN_API_KEY: "{{ lookup('env', 'TINYVAULT_ADMIN_API_KEY') | default('', true) }}"
        TINYVAULT_WEBHOOK_SECRET: "{{ lookup('env', 'TINYVAULT_WEBHOOK_SECRET') | default('', true) }}"
        TINYVAULT_DEBUG: "{{ lookup('env', 'TINYVAULT_DEBUG') | default('false', true) }}"
        TINYVAULT_APP_NAME: "{{ lookup('env', 'TINYVAULT_APP_NAME') | default('TinyVault', true) }}"

    - name: Build Docker container
      community.docker.docker_image:
        name: tinyvault-app
        build:
          path: /opt/tinyvault
        source: build
        pull: yes
        args:
          ADMIN_API_KEY: "{{ lookup('env', 'TINYVAULT_ADMIN_API_KEY') | default('', true) }}"
          DB_URL: "{{ lookup('env', 'TINYVAULT_DB_URL') | default('sqlite+aiosqlite:///./data/tinyvault.db', true) }}"
          TELEGRAM_BOT_TOKEN: "{{ lookup('env', 'TINYVAULT_TELEGRAM_BOT_TOKEN') | default('', true) }}"
          WEBHOOK_SECRET: "{{ lookup('env', 'TINYVAULT_WEBHOOK_SECRET') | default('', true) }}"
          DEBUG: "{{ lookup('env', 'TINYVAULT_DEBUG') | default('false', true) }}"
          EC2_HOST: "{{ lookup('env', 'EC2_HOST') | default('localhost', true) }}"
          APP_NAME: "{{ lookup('env', 'TINYVAULT_APP_NAME') | default('TinyVault', true) }}"

    - name: Run Docker container
      community.docker.docker_container:
        name: tinyvault-app
        image: tinyvault-app
        state: started
        restart_policy: always
        ports:
          - "80:8000"
        env:
          DB_URL: "{{ lookup('env', 'TINYVAULT_DB_URL') | default('sqlite+aiosqlite:///./data/tinyvault.db', true) }}"
          TELEGRAM_BOT_TOKEN: "{{ lookup('env', 'TINYVAULT_TELEGRAM_BOT_TOKEN') | default('', true) }}"
          ADMIN_API_KEY: "{{ lookup('env', 'TINYVAULT_ADMIN_API_KEY') | default('', true) }}"
          WEBHOOK_SECRET: "{{ lookup('env', 'TINYVAULT_WEBHOOK_SECRET') | default('', true) }}"
          DEBUG: "{{ lookup('env', 'TINYVAULT_DEBUG') | default('false', true) }}"
          EC2_HOST: "{{ lookup('env', 'EC2_HOST') | default('localhost', true) }}"
          APP_NAME: "{{ lookup('env', 'TINYVAULT_APP_NAME') | default('TinyVault', true) }}"

    - name: Wait for container to be ready
      pause:
        seconds: 10